site_name: VLS-4D
repo_url: https://github.com/3dgeo-heidelberg/vls-4d
docs_dir: ../docs
site_dir: ../site

theme:
  logo: ../docs/img/3DGeo_globe_256.png
  favicon: ../docs/img/3dgeo.ico
  name: material
  custom_dir: overrides
  palette:
    primary: green
    accent: light-green
  features:
    - search.highlight
    - content.code.copy
    - navigation.top
    - navigation.footer
use_directory_urls: false
extra_css:
  - css/custom.css
plugins:
  - mkdocs-jupyter:
      include_source: True
      include_requirejs: true
      ignore_h1_titles: True
  - search
markdown_extensions:
  - attr_list
  - abbr

nav:
- 'Home': 'index.md'
- '1 Concept of a static snapshot per epoch': '01_static_snapshot_per_epoch.ipynb'
- '2 Concept of several static snapshots within an epoch': '02_static_snapshots_within_epoch.ipynb'
- '3 Concept of animation within the simulator': '03_animation_within_the_simulator.ipynb'